import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:tiffin_mate/data/models/tiffin_entry.dart';

class PdfService {
  Future<void> generateAndShareInvoice(
    List<TiffinEntry> tiffins,
    String userName,
    DateTime? startDate,
    DateTime? endDate,
  ) async {
    final pdf = pw.Document();

    // Load a font if needed, or use default
    final font = await PdfGoogleFonts.poppinsRegular();
    final fontBold = await PdfGoogleFonts.poppinsBold();

    final totalAmount = tiffins.fold(0.0, (sum, item) => sum + item.price);
    final dateRangeText = (startDate != null && endDate != null)
        ? "${DateFormat('dd MMM').format(startDate)} - ${DateFormat('dd MMM').format(endDate)}"
        : "Full History";

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          theme: pw.ThemeData.withFont(base: font, bold: fontBold),
        ),
        build: (context) => [
          _buildHeader(userName, dateRangeText),
          pw.SizedBox(height: 20),
          _buildSummary(tiffins.length, totalAmount),
          pw.SizedBox(height: 20),
          _buildTable(tiffins),
          pw.SizedBox(height: 20),
          _buildFooter(),
        ],
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename:
          'tiffin_bill_${DateFormat('yyyyMMdd').format(DateTime.now())}.pdf',
    );
  }

  pw.Widget _buildHeader(String userName, String dateRange) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          "TIFFIN MATE",
          style: pw.TextStyle(
            fontSize: 24,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.orange,
          ),
        ),
        pw.SizedBox(height: 8),
        pw.Text("Bill Summary for: $userName"),
        pw.Text("Period: $dateRange"),
        pw.Divider(),
      ],
    );
  }

  pw.Widget _buildSummary(int count, double total) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text("Total Tiffins: $count"),
          pw.Text(
            "Total Amount: INR ${total.toStringAsFixed(0)}",
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildTable(List<TiffinEntry> tiffins) {
    return pw.TableHelper.fromTextArray(
      headers: ['Date', 'Type', 'Menu', 'Price'],
      data: tiffins
          .map(
            (e) => [
              DateFormat('dd MMM yyyy').format(e.date),
              e.type,
              e.menu.isEmpty ? '-' : e.menu,
              e.price.toStringAsFixed(0),
            ],
          )
          .toList(),
      border: null,
      headerStyle: pw.TextStyle(
        fontWeight: pw.FontWeight.bold,
        color: PdfColors.white,
      ),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.orange),
      cellHeight: 30,
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.centerLeft,
        2: pw.Alignment.centerLeft,
        3: pw.Alignment.centerRight,
      },
    );
  }

  pw.Widget _buildFooter() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Divider(),
        pw.SizedBox(height: 10),
        pw.Text(
          "Generated by TiffinMate",
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
        ),
      ],
    );
  }
}
